#!/bin/sh

[ -f "$WGET_OVERRIDE" ] || exit 1

while getopts ":O:" OPTION; do
    case "$OPTION" in
        O)
            path="$WGET_OVERRIDE"
            echo "$@" | grep 'offset=0$' >/dev/null || path="test/fixtures/endpoint-response/elspotprices_empty"
            cat "$path" > "$OPTARG"
            exit 0
            ;;
        *)
            ;;
    esac
done

echo "-O not provided among: $*"
exit 1