services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:ro
    working_dir: /workspace
  redocly:
    image: redocly/cli
    volumes:
      - .:/spec:ro
  dockerlint:
    image: hadolint/hadolint
    entrypoint: /bin/hadolint --ignore DL3018
    volumes:
      - .:/workspace:ro
    working_dir: /workspace
  makelint:
    image: mrtazz/checkmake
    volumes:
      - ./Makefile:/Makefile:ro
  markdownlint:
    image: ghcr.io/igorshubovych/markdownlint-cli
    volumes:
      - .:/workspace:ro
    working_dir: /workspace
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      URL: /openapi.yaml
    ports:
      - "8081:8080"
    volumes:
      - ./resources/openapi.yaml:/usr/share/nginx/html/openapi.yaml
