services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:ro
    working_dir: /workspace
  redocly:
    image: redocly/cli
    volumes:
      - .:/spec:ro
  dockerlint:
    image: redcoolbeans/dockerlint
    volumes:
      - ./Dockerfile:/Dockerfile:ro
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      URL: /openapi.yaml
    ports:
      - "8081:8080"
    volumes:
      - ./resources/openapi.yaml:/usr/share/nginx/html/openapi.yaml
