name: Health Checks

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}
  push: {} # FIXME: remove

jobs:
  grid:
    uses: ./.github/workflows/health-check-grid.yaml

  networks:
    uses: ./.github/workflows/health-check-networks.yaml
    with:
      publish-branch: gh-pages
