name: Grid Health Check

on:
  workflow_call: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Define matrix
    steps:
      - uses: actions/checkout@v4

      - shell: bash
        name: Setup configuration
        run: |
          NOW=$(date +"%s")

          jq -rc '.[] | select(.capabilities | index("grid") | .) | .zone' < configuration/zones.json | while read -r AREA; do
            EXPIRATION=$(jq "[.${AREA} | .[].to] | max" < configuration/grid.json)
            DIFFERENCE=$((EXPIRATION-NOW))
            DAYS=$((DIFFERENCE/86400))
            echo "$AREA is valid for $DAYS days until $(date -d "@$EXPIRATION" +"%Y-%m-%dT%H:%M:%S%z")"
          done

# https://github.com/JasonEtco/create-an-issue
