name: Grid Health Check

on:
  workflow_call: {}

permissions:
  contents: read
  issues: write

env:
  minimum-data-amount: 90

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Define matrix
    outputs:
      matrix: ${{ env.matrix }}
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        name: Setup configuration
        run: |
          NOW=$(date +"%s")

          jq -rc '.[] | select(.capabilities | index("grid") | .) | .zone' < configuration/zones.json | while read -r AREA; do
            EXPIRATION=$(jq "[.${AREA} | .[].to] | max" < configuration/grid.json)
            DIFFERENCE=$((EXPIRATION-NOW))
            DAYS=$((DIFFERENCE/86400))
            FORMATTED=$(date -d "@$EXPIRATION" +"%Y-%m-%d")
            >&2 echo "$AREA is valid for $DAYS days until $(date -d "@$EXPIRATION" +"%Y-%m-%dT%H:%M:%S%z")"

            if [ "$DAYS" -lt "${{ env.minimum-data-amount }}" ]; then
              jq -nc --arg zone "$AREA" --arg expiration "$FORMATTED" '{zone: $zone, expiration: $expiration}'
            fi
          done | jq -sc > matrix

          echo '::group::Matrix'
          jq < matrix
          echo '::endgroup::'

          echo "matrix=$(jq -c < matrix)" >> "$GITHUB_ENV"

  create-issue:
    runs-on: ubuntu-latest
    name: Create issue
    if: github.ref == 'refs/heads/main'
    needs: setup
    strategy:
      matrix:
        build: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        name: Setup configuration
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue list --label "automated" --limit 1 --state open --search "Out of date - grid ${{ matrix.zone }}" --json number,title | jq -c '.[]' | tee issues
          [ -s issues ] || exit 0

          echo "The current data for grid ${{ matrix.zone }} will expire at ${{ matrix.expiration }}" | gh issue create --assignee codereaper --body-file - --label automated --title "Update ${{ matrix.zone }}"
