name: Health Checks

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/health-check*.yaml
      - .github/actions/handle-issue

jobs:
  grid:
    name: Grid
    uses: ./.github/workflows/health-check-grid.yaml

  networks:
    name: Networks
    uses: ./.github/workflows/health-check-networks.yaml
    with:
      publish-branch: gh-pages

  integrity:
    name: Integrity
    uses: ./.github/workflows/health-check-integrity.yaml
    with:
      publish-branch: gh-pages

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make unit-tests
        shell: bash
