name: Pull data

on:
  # TODO: after successful run on main, enable schedule
  # schedule:
  #   - cron: '5 12,13,14,15,18,21 * * *'
  workflow_dispatch: {}

jobs:
  setup-matrix:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Setup matrix
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.POWERCASTDEPLOY }}
          ref: gh-pages2 # TODO: after successful run on main, set this to: gh-pages
          path: gh-pages

      - shell: bash
        name: Pull data
        run: |
          mkdir -p ./gh-pages/data/ > /dev/null

          sh .github/scripts/data-matrix.sh .config.json ./gh-pages/data/ | jq -rc '.[]' | while read CONFIG; do
            ZONE=$(echo "$ITEM" | jq -r '.zone')
            ENDDATE=$(echo "$ITEM" | jq -r '.endDate')

            sh .github/scripts/data-pull.sh $ZONE ${ENDDATE} > "${ZONE}.generated"
          done

      - shell: bash
        name: Write data
        run: |
          for GENERATED in *.generated; do
            ZONE=$(basename $GENERATED .generated)
            echo "Using generated data for ${ZONE}..."
            sh .github/scripts/data-write.sh $GENERATED ./gh-pages/data/ $ZONE
          done

      - shell: bash
        name: Index data
        run: |
          sh .github/scripts/data-write.sh .config.json ./gh-pages/data/ /data > ./gh-pages/data/latest.json

      - uses: EndBug/add-and-commit@v9
        name: Publish data
        with:
          cwd: gh-pages
          add: data
          push: true
          default_author: github_actions
          message: Update new data to GitHub pages via workflow
