name: Contents

on:
  schedule:
    - cron: '0 * * * *'
    - cron: '*/5 12 * * *'

  workflow_dispatch: {}
  push:
    branches:
      - main

concurrency: pulling-data

env:
  publish-branch: gh-pages

jobs:
  content-check:
    runs-on: ubuntu-latest
    name: Content check
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check content availability
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "CONTENTS_AVAILABLE=0" >> "$GITHUB_ENV"

          lastChange=$(gh api "/repos/${{ github.repository }}/commits?path=api/energy-price/&sha=${{ env.publish-branch }}&per_page=1" | jq -r '.[0].commit.committer.date | fromdateiso8601')

          if [ $(($lastChange+(3600*23))) -gt $(date +%s) ]; then
            echo "CONTENTS_AVAILABLE=1" >> "$GITHUB_ENV"
          fi

      - name: Fetch contents
        if: ${{ env.CONTENTS_AVAILABLE =! '0' }}
        uses: ./.github/workflows/update-contents.yaml
