name: Pull data

on:
  schedule:
    - cron: '5 12,13,14 * * *'
  workflow_dispatch: {}

env:
  publish-branch: gh-pages

jobs:
  update-energy-price-data:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Update energy price data
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.POWERCASTDEPLOY }}
          ref: ${{ env.publish-branch }}
          path: github-pages

      - shell: bash
        id: update-energy-price-data
        name: Pull data
        run: |
          mkdir -p ./github-pages/api/energy-price/ > /dev/null

          echo "::set-output name=changed::false"

          sh .github/scripts/energy-price-data-matrix.sh .config.json ./github-pages/api/energy-price/ | jq -rc '.[]' | while read CONFIG; do
            echo "::set-output name=changed::true"

            ZONE=$(echo "$CONFIG" | jq -r '.zone')
            ENDDATE=$(echo "$CONFIG" | jq -r '.endDate')

            echo "Pull data for ${ZONE} until ${ENDDATE}..."
            sh .github/scripts/energy-price-data-pull.sh $ZONE $ENDDATE > "${ZONE}.generated"
          done

      - shell: bash
        name: Write data
        if: steps.update-energy-price-data.outputs.changed == 'true'
        run: |
          for GENERATED in *.generated; do
            [ -f "$GENERATED" ] || continue
            ZONE=$(basename $GENERATED .generated)
            echo "Using generated data for ${ZONE}..."
            sh .github/scripts/energy-price-data-write.sh $GENERATED ./github-pages/api/energy-price/ $ZONE
          done

      - shell: bash
        name: Index data
        if: steps.update-energy-price-data.outputs.changed == 'true'
        run: |
          sh .github/scripts/energy-price-data-index.sh .config.json ./github-pages/api/energy-price/ /api/energy-price > ./github-pages/api/energy-price/latest.json

      - uses: EndBug/add-and-commit@v9
        name: Publish data
        if: steps.update-energy-price-data.outputs.changed == 'true'
        with:
          cwd: github-pages
          add: api/energy-price/
          push: --set-upstream origin ${{ env.publish-branch }}
          default_author: github_actions
          message: Publish new data via workflow

  update-energy-price-visualization:
    if: github.ref == 'refs/heads/main' && needs.update-energy-price-data.steps.update-energy-price-data.outputs.changed == 'true'
    runs-on: ubuntu-latest
    needs: update-energy-price-data
    name: Update energy price visualization
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.POWERCASTDEPLOY }}
          ref: ${{ env.publish-branch }}
          path: github-pages

      - shell: bash
        name: Pull data
        run: |
          set -e

          [ -d ./github-pages/api/energy-price/ ] || exit 0

          cp .github/resources/energy-price-graph/index.html ./github-pages/
          sh .github/scripts/energy-price-data-graph.sh .config.json ./github-pages/api/energy-price/ > ./github-pages/data.js

      - uses: EndBug/add-and-commit@v9
        name: Publish graph
        with:
          cwd: github-pages
          add: data.js
          push: --set-upstream origin ${{ env.publish-branch }}
          default_author: github_actions
          message: Publish new graph via workflow
