name: Pull data

on:
  # schedule:
  #   - cron: '5 0,4,8,12,16,10 * * *'
  workflow_dispatch: {}

env:
  publish-branch: gh-pages

jobs:
  update-energy-price-data:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Update energy price data
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.POWERCASTDEPLOY }}
          ref: ${{ env.publish-branch }}
          path: github-pages

      - shell: bash
        name: Setup configuration
        run: |
          sh .github/scripts/energy-price-data-matrix.sh .config.json ./github-pages/api/energy-price/ | tee configuration.json

      - shell: bash
        name: Pull data
        run: |
          mkdir -p ./github-pages/api/energy-price/ > /dev/null

          jq -rc '.[]' configuration.json | while read CONFIG; do
            ZONE=$(echo "$CONFIG" | jq -r '.zone')
            LATEST=$(echo "$CONFIG" | jq -r '.latest')

            echo "Pull data for ${ZONE} until ${LATEST}..."
            sh .github/scripts/energy-price-data-pull.sh $ZONE $LATEST > "${ZONE}.generated"
          done

      - shell: bash
        id: update-energy-price-data
        name: Write data
        run: |
          echo "::set-output name=changed::false"

          jq -rc '.[]' configuration.json | while read CONFIG; do
            ZONE=$(echo "$CONFIG" | jq -r '.zone')
            LATEST=$(echo "$CONFIG" | jq -r '.latest')
            GENERATED="${ZONE}.generated"

            [ -f "$GENERATED" ] || continue

            NEW=$(sh .github/scripts/energy-price-data-freshness-file.sh $GENERATED $LATEST)

            echo "Checking data for ${ZONE}:\n - ${LATEST} - current data\n - ${NEW} - new data"
            if [ $NEW -gt $LATEST ]; then
              echo "::set-output name=changed::true"
            fi
          done

      - shell: bash
        if: steps.update-energy-price-data.outputs.changed == 'true'
        name: Write data
        run: |
          for GENERATED in *.generated; do
            [ -f "$GENERATED" ] || continue
            ZONE=$(basename $GENERATED .generated)
            echo "Using generated data for ${ZONE}..."
            sh .github/scripts/energy-price-data-write.sh $GENERATED ./github-pages/api/energy-price/ $ZONE
          done

      - shell: bash
        if: steps.update-energy-price-data.outputs.changed == 'true'
        name: Index data
        run: |
          sh .github/scripts/energy-price-data-index.sh .config.json ./github-pages/api/energy-price/ /api/energy-price > ./github-pages/api/energy-price/latest.json

      # - uses: EndBug/add-and-commit@v9
      #   if: steps.update-energy-price-data.outputs.changed == 'true'
      #   name: Publish data
      #   with:
      #     cwd: github-pages
      #     add: api/energy-price/
      #     push: --set-upstream origin ${{ env.publish-branch }}
      #     default_author: github_actions
      #     message: Publish new data via workflow
